export const eventsMock = [
  {
    name: "Clube do Laço Coração Pantaneiro",
    teams: 10,
    status: "Ativo",
    date: "09 a 11 de Junho",
  },
  { name: "Festa Junina de São Pedro", teams: 8, status: "Ativo", date: "15 a 17 de Junho" },
  { name: "Campeonato Regional de Laço", teams: 12, status: "Inativo", date: "20 a 22 de Junho" },
  { name: "Encontro Nacional de Cavaleiros", teams: 15, status: "Ativo", date: "01 a 03 de Julho" },
  { name: "Festa do Peão de Boiadeiro", teams: 9, status: "Ativo", date: "10 a 12 de Julho" },
  {
    name: "Campeonato de Montaria em Touros",
    teams: 14,
    status: "Inativo",
    date: "18 a 20 de Julho",
  },
  { name: "Festival Sertanejo de Primavera", teams: 11, status: "Ativo", date: "25 a 27 de Julho" },
  { name: "Rodeio do Cerrado", teams: 13, status: "Ativo", date: "05 a 07 de Agosto" },
  { name: "Encontro de Laçadores do Sul", teams: 7, status: "Inativo", date: "12 a 14 de Agosto" },
  { name: "Festa da Cavalgada Regional", teams: 10, status: "Ativo", date: "19 a 21 de Agosto" },
  { name: "Campeonato Estadual de Laço", teams: 16, status: "Ativo", date: "26 a 28 de Agosto" },
  { name: "Festa do Cowboy", teams: 9, status: "Inativo", date: "02 a 04 de Setembro" },
  { name: "Festival de Música Sertaneja", teams: 12, status: "Ativo", date: "09 a 11 de Setembro" },
  {
    name: "Encontro Nacional de Vaqueiros",
    teams: 14,
    status: "Ativo",
    date: "16 a 18 de Setembro",
  },
  { name: "Campeonato de Laço Infantil", teams: 8, status: "Inativo", date: "23 a 25 de Setembro" },
  { name: "Rodeio de Outono", teams: 10, status: "Ativo", date: "30 de Setembro a 02 de Outubro" },
  { name: "Festa do Peão de Primavera", teams: 11, status: "Ativo", date: "07 a 09 de Outubro" },
  {
    name: "Campeonato Regional de Montaria",
    teams: 13,
    status: "Inativo",
    date: "14 a 16 de Outubro",
  },
  { name: "Encontro de Laçadores do Norte", teams: 9, status: "Ativo", date: "21 a 23 de Outubro" },
  { name: "Festival Sertanejo de Verão", teams: 15, status: "Ativo", date: "28 a 30 de Outubro" },
  { name: "Rodeio do Pantanal", teams: 12, status: "Inativo", date: "04 a 06 de Novembro" },
  { name: "Festa da Cavalgada Nacional", teams: 10, status: "Ativo", date: "11 a 13 de Novembro" },
  {
    name: "Campeonato Estadual de Montaria",
    teams: 14,
    status: "Ativo",
    date: "18 a 20 de Novembro",
  },
  { name: "Festa do Cowboy Regional", teams: 8, status: "Inativo", date: "25 a 27 de Novembro" },
  { name: "Festival de Música Caipira", teams: 9, status: "Ativo", date: "02 a 04 de Dezembro" },
  {
    name: "Encontro Nacional de Cavaleiros",
    teams: 13,
    status: "Ativo",
    date: "09 a 11 de Dezembro",
  },
  { name: "Campeonato de Laço Juvenil", teams: 10, status: "Inativo", date: "16 a 18 de Dezembro" },
  { name: "Rodeio de Verão", teams: 14, status: "Ativo", date: "23 a 25 de Dezembro" },
  {
    name: "Festa do Peão do Interior",
    teams: 12,
    status: "Ativo",
    date: "30 de Dezembro a 01 de Janeiro",
  },
  {
    name: "Campeonato Regional de Laço Noturno",
    teams: 11,
    status: "Inativo",
    date: "06 a 08 de Janeiro",
  },
];
